#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Sean Kammerich
"""Validate an inline MLP-island bound and emit its per-block/die scale table.

The persistent island scales each ANE's fc2 activation independently. A single
global scale either underflows early blocks or saturates the concentrated late
block, so the table is part of the arithmetic contract rather than tuning.

    python3 Tools/ANE/mlp_island_scales.py \
        /path/mlp-island-calibration.json --format swift

This tool proves only saturation. Precision remains a separate gate: every
scale smaller than the oracle-validated floor for its block must be exercised
against a captured production activation before the table can ship.
"""

import argparse
import json
import math
import re
import sys

LABEL = re.compile(r"^fc2 island b(\d{2}) ane([01]) split4$")
EXPECTED_BLOCKS = 50
MARGIN_LIMIT = 16384.0  # half of the ANE 2^15 saturation cliff


def is_power_of_two(value):
    if not math.isfinite(value) or value <= 0:
        return False
    mantissa, _ = math.frexp(value)
    return mantissa == 0.5


def load_table(path, neurons_per_die=None):
    with open(path) as f:
        document = json.load(f)

    table = {}
    errors = []
    for label, row in document.items():
        match = LABEL.match(label)
        if not match:
            continue
        block, die = int(match.group(1)), int(match.group(2))
        key = (block, die)
        if key in table:
            errors.append("duplicate %s" % label)
            continue
        try:
            bound = float(row["bound"])
            scale = float(row["requiredScale2x"])
        except (KeyError, TypeError, ValueError) as error:
            errors.append("%s has invalid bound/scale: %s" % (label, error))
            continue
        if not is_power_of_two(scale) or scale > 1.0:
            errors.append("%s scale %g is not a power of two <= 1" % (label, scale))
        if bound * scale >= MARGIN_LIMIT:
            errors.append("%s does not retain 2x headroom: %g * %g >= %g" %
                          (label, bound, scale, MARGIN_LIMIT))
        if scale * 2 <= 1.0 and bound * scale * 2 < MARGIN_LIMIT:
            errors.append("%s scale %g is smaller than necessary" % (label, scale))
        if neurons_per_die is not None:
            expected_range = ([14336 - 2 * neurons_per_die, 14336 - neurons_per_die]
                              if die == 0 else [14336 - neurons_per_die, 14336])
            if row.get("contraction") != expected_range:
                errors.append("%s contraction %r != expected %r" %
                              (label, row.get("contraction"), expected_range))
        table[key] = {"bound": bound, "scale": scale,
                      "progress": float(row.get("progress", -1))}

    expected = {(block, die) for block in range(EXPECTED_BLOCKS) for die in range(2)}
    missing = sorted(expected - table.keys())
    extra = sorted(table.keys() - expected)
    if missing:
        errors.append("missing block/die entries: %s" % missing)
    if extra:
        errors.append("unexpected block/die entries: %s" % extra)
    if errors:
        raise ValueError("\n".join(errors))
    return table


def scale_literal(value):
    if value == 1.0:
        return "1"
    return "1.0 / %d.0" % round(1.0 / value)


def emit_swift(table):
    print("// Generated by Tools/ANE/mlp_island_scales.py; do not hand-edit.")
    print("static let mlpIslandFC2Scales: [(Float, Float)] = [")
    for block in range(EXPECTED_BLOCKS):
        a = scale_literal(table[(block, 0)]["scale"])
        b = scale_literal(table[(block, 1)]["scale"])
        print("    (%-12s, %-12s), // block %02d" % (a, b, block))
    print("]")


def emit_json(table):
    rows = [{"block": block,
             "ane0": table[(block, 0)]["scale"],
             "ane1": table[(block, 1)]["scale"]}
            for block in range(EXPECTED_BLOCKS)]
    print(json.dumps(rows, indent=2))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("calibration", help="JSON written by H3_ANE_BOUND_MLP_ISLAND_ONLY")
    parser.add_argument("--format", choices=("summary", "swift", "json"), default="summary")
    parser.add_argument("--neurons-per-die", type=int,
                        help="also require the exact two suffix contraction ranges")
    args = parser.parse_args()
    try:
        table = load_table(args.calibration, args.neurons_per_die)
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print("invalid MLP-island calibration: %s" % error, file=sys.stderr)
        return 2

    if args.format == "swift":
        emit_swift(table)
    elif args.format == "json":
        emit_json(table)
    else:
        counts = {}
        for row in table.values():
            counts[row["scale"]] = counts.get(row["scale"], 0) + 1
        print("validated %d blocks x 2 ANE ranges with 2x saturation headroom" %
              EXPECTED_BLOCKS)
        for scale, count in sorted(counts.items(), reverse=True):
            print("  %-8s %3d range(s)" % (scale_literal(scale), count))
        worst_key = min(table, key=lambda key: table[key]["scale"])
        worst = table[worst_key]
        print("worst: block %02d ane%d, bound %.0f, scale %s, observed at %.0f%%" %
              (worst_key[0], worst_key[1], worst["bound"],
               scale_literal(worst["scale"]), 100 * worst["progress"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
