// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sean Kammerich

import Foundation
import Metal
import MLX
import MLXNN
import H3Foundation
import H3ANEBridge

/// Persistent tensor-parallel H3 MLP.
///
/// The calibrated suffix is four 512-neuron ranges per die. Production timing
/// activates the first three on each ANE and returns the fourth pair to Metal,
/// balancing shared-fabric execution without invalidating the range proof.
/// Gate/up outputs remain
/// in IOSurfaces, the Metal seam writes each gated activation directly in the
/// next program's input orientation, and only hidden-width fc2 partials cross
/// the final seam.
///
/// This remains explicitly experimental. Any refusal before submission returns
/// nil so the caller uses its established path. Any failure after submission
/// recomputes the complete MLP on the GPU; a partial result is never returned.
package enum ANEMLPIslandBackend {
    static let isEnabled: Bool = ANELinearBackend.isEnabled
        && ProcessInfo.processInfo.environment["H3_ANE_MLP_ISLAND"] == "1"

    static let neuronsPerDie = 2_048
    static let pieces = 4
    // Shared-fabric production timing made four active pieces ANE-bound. Three
    // retains exact calibrated 512-neuron ranges while moving 1,024 neurons
    // back to the GPU; the fourth partial surface remains zero for the fixed
    // native merge ABI.
    static let activePieces = 3
    // Four contraction pieces keep the ANE moving under simultaneous GPU load:
    // the unsplit form is faster alone but fell to 0.911x as a hybrid, while
    // this form reached 1.061x before ownership rebalancing.
    static let contractionSplits = 4
    static let neuronsPerPiece = neuronsPerDie / pieces
    // Derived, not restated. These were hand-written constants, and
    // `expectedHidden` was written as 7,168 — which is `innerDim`, the
    // attention width (56 heads x 128), not the MLP's hidden size of 5,376.
    // Every guard below keys on it, so the island declined every real block
    // and had never once routed on this model. It was invisible because the
    // conformance test built its tensors from this same constant: it validated
    // the island against its own assumption, and would have passed at any
    // value. See `docs/ANE_STATUS.md`.
    static let expectedFFN = H3Config().ffnHidden
    static let expectedHidden = H3Config().hiddenSize
    // The faithful fc1 bound peaks near 72, hundreds of times below the ANE's
    // 2^15 partial-sum cliff, so scaling this contraction buys no safety. The
    // generic projection route uses 1/16, but carrying that into the island
    // flushes small products before SwiGLU and measured 1.3% relative error on
    // the complete ANE contribution. Keep fc1 unscaled; only the independently
    // calibrated fc2 activation scales below vary by block and die.
    static let inputScale: Float = 1

    /// Generated from the exact `GPU=10240, ANE0=2048, ANE1=2048` faithful
    /// calibration. Every entry is the largest power-of-two scale retaining a
    /// factor-of-two margin below the ANE's silent 2^15 partial-sum failure.
    // Generated by Tools/ANE/mlp_island_scales.py; do not hand-edit.
    static let fc2Scales: [(Float, Float)] = [
        (1, 1), // block 00
        (1, 1), // block 01
        (1, 1), // block 02
        (1, 1), // block 03
        (1, 1), // block 04
        (1, 1), // block 05
        (1, 1), // block 06
        (1, 1), // block 07
        (1, 1), // block 08
        (1, 1), // block 09
        (1, 1), // block 10
        (1, 1), // block 11
        (1, 1), // block 12
        (1, 1), // block 13
        (1, 1), // block 14
        (1, 1), // block 15
        (1, 1), // block 16
        (1, 1), // block 17
        (1, 1), // block 18
        (1, 1), // block 19
        (1, 1), // block 20
        (1, 1), // block 21
        (1, 1), // block 22
        (1, 1), // block 23
        (1, 1), // block 24
        (1, 1), // block 25
        (1, 1), // block 26
        (1, 1), // block 27
        (1, 1), // block 28
        (1, 1), // block 29
        (1, 1), // block 30
        (1, 1), // block 31
        (1, 1), // block 32
        (1.0 / 2.0, 1), // block 33
        (1, 1), // block 34
        (1, 1), // block 35
        (1.0 / 4.0, 1.0 / 2.0), // block 36
        (1, 1), // block 37
        (1.0 / 2.0, 1.0 / 2.0), // block 38
        (1, 1.0 / 256.0), // block 39
        (1.0 / 2.0, 1.0 / 2.0), // block 40
        (1.0 / 2.0, 1.0 / 2.0), // block 41
        (1.0 / 2.0, 1), // block 42
        (1.0 / 4.0, 1.0 / 32.0), // block 43
        (1.0 / 8.0, 1.0 / 32.0), // block 44
        (1.0 / 2.0, 1.0 / 2.0), // block 45
        (1, 1.0 / 2.0), // block 46
        (1.0 / 2.0, 1.0 / 8.0), // block 47
        (1.0 / 4.0, 1.0 / 64.0), // block 48
        (1.0 / 8.0, 1.0 / 16.0), // block 49
    ]

    package struct Partition: Equatable {
        package let gpu: Range<Int>
        package let ane0: Range<Int>
        package let ane1: Range<Int>
    }

    package static func partition(ffn: Int) -> Partition? {
        guard ffn == expectedFFN else { return nil }
        let gpuEnd = ffn - 2 * neuronsPerDie
        return Partition(gpu: 0 ..< gpuEnd,
                         ane0: gpuEnd ..< (gpuEnd + neuronsPerDie),
                         ane1: (gpuEnd + neuronsPerDie) ..< ffn)
    }

    fileprivate final class Engine: @unchecked Sendable {
        static let shared = Engine()
        private let queue = DispatchQueue(label: "h3.ane.mlp-island", qos: .userInitiated)

        final class Job: @unchecked Sendable {
            private let done = DispatchSemaphore(value: 0)
            private var result = false
            func settle(_ value: Bool) { result = value; done.signal() }
            func wait() -> Bool { done.wait(); return result }
        }

        func submit(_ work: @escaping @Sendable () -> Bool) -> Job {
            let job = Job()
            queue.async { job.settle(ANELinearBackend.EngineMeter.measure(work)) }
            return job
        }
    }

    fileprivate final class Piece: @unchecked Sendable {
        let gate0: [OpaquePointer], gate1: [OpaquePointer]
        let up0: [OpaquePointer], up1: [OpaquePointer]
        let activation0: OpaquePointer, activation1: OpaquePointer
        let partial0: OpaquePointer, partial1: OpaquePointer

        init?(s: Int, hidden: Int) {
            var made: [OpaquePointer] = []
            func tensor(_ rows: Int, _ width: Int) -> OpaquePointer? {
                guard let value = h3_ane_tensor_create(Int32(rows), Int32(width)) else { return nil }
                made.append(value); return value
            }
            var gate0: [OpaquePointer] = [], gate1: [OpaquePointer] = []
            var up0: [OpaquePointer] = [], up1: [OpaquePointer] = []
            for _ in 0 ..< contractionSplits {
                guard let g0 = tensor(s, neuronsPerPiece),
                      let g1 = tensor(s, neuronsPerPiece),
                      let u0 = tensor(s, neuronsPerPiece),
                      let u1 = tensor(s, neuronsPerPiece)
                else {
                    for value in made { h3_ane_tensor_free(value) }
                    return nil
                }
                gate0.append(g0); gate1.append(g1)
                up0.append(u0); up1.append(u1)
            }
            guard let activation0 = tensor(neuronsPerPiece, s),
                  let activation1 = tensor(neuronsPerPiece, s),
                  let partial0 = tensor(s, hidden),
                  let partial1 = tensor(s, hidden)
            else {
                for value in made { h3_ane_tensor_free(value) }
                return nil
            }
            self.gate0 = gate0; self.gate1 = gate1
            self.up0 = up0; self.up1 = up1
            self.activation0 = activation0; self.activation1 = activation1
            self.partial0 = partial0; self.partial1 = partial1
        }

        deinit {
            for value in gate0 + gate1 + up0 + up1 +
                [activation0, activation1, partial0, partial1] {
                h3_ane_tensor_free(value)
            }
        }
    }

    fileprivate final class Slot: @unchecked Sendable {
        let xs: [OpaquePointer]
        let pieces: [Piece]
        init?(s: Int, k: Int, hidden: Int) {
            var xs: [OpaquePointer] = []
            for _ in 0 ..< contractionSplits {
                guard let x = h3_ane_tensor_create(
                    Int32(k / contractionSplits), Int32(s)
                ) else {
                    for value in xs { h3_ane_tensor_free(value) }
                    return nil
                }
                xs.append(x)
            }
            var made: [Piece] = []
            // Four partials are fixed in the native merge ABI. The inactive
            // fourth stays zero for the slot's lifetime.
            for _ in 0 ..< ANEMLPIslandBackend.pieces {
                guard let piece = Piece(s: s, hidden: hidden) else {
                    for value in xs { h3_ane_tensor_free(value) }
                    return nil
                }
                made.append(piece)
            }
            self.xs = xs; self.pieces = made
        }
        deinit { for value in xs { h3_ane_tensor_free(value) } }
    }

    fileprivate final class Session: @unchecked Sendable {
        final class Programs: @unchecked Sendable {
            let gate0: [OpaquePointer], gate1: [OpaquePointer]
            let up0: [OpaquePointer], up1: [OpaquePointer]
            let down0: OpaquePointer, down1: OpaquePointer

            init?(s: Int, k: Int, hidden: Int) {
                var made: [OpaquePointer] = []
                func program(_ depth: Int, _ width: Int) -> OpaquePointer? {
                    guard let value = h3_ane_program_create(
                        Int32(s), Int32(depth), Int32(width)
                    ) else { return nil }
                    made.append(value)
                    return value
                }
                var gate0: [OpaquePointer] = [], gate1: [OpaquePointer] = []
                var up0: [OpaquePointer] = [], up1: [OpaquePointer] = []
                for _ in 0 ..< contractionSplits {
                    guard let g0 = program(k / contractionSplits, neuronsPerPiece),
                          let g1 = program(k / contractionSplits, neuronsPerPiece),
                          let u0 = program(k / contractionSplits, neuronsPerPiece),
                          let u1 = program(k / contractionSplits, neuronsPerPiece)
                    else {
                        for value in made { h3_ane_program_free(value) }
                        return nil
                    }
                    gate0.append(g0); gate1.append(g1)
                    up0.append(u0); up1.append(u1)
                }
                guard let down0 = program(neuronsPerPiece, hidden),
                      let down1 = program(neuronsPerPiece, hidden)
                else {
                    for value in made { h3_ane_program_free(value) }
                    return nil
                }
                self.gate0 = gate0; self.gate1 = gate1
                self.up0 = up0; self.up1 = up1
                self.down0 = down0; self.down1 = down1
            }

            deinit {
                for value in gate0 + gate1 + up0 + up1 + [down0, down1] {
                    h3_ane_program_free(value)
                }
            }
        }

        let s: Int, k: Int, hidden: Int
        let programs: [Programs]
        private let lock = NSLock()
        private let available = DispatchSemaphore(value: 2)
        private var idle: [Slot]
        private var poisoned = false

        init?(requestedS: Int, k: Int, hidden: Int) {
            let s = ANELinearBackend.paddedSequence(requestedS)
            var programs: [Programs] = []
            for _ in 0 ..< ANEMLPIslandBackend.activePieces {
                guard let value = Programs(s: s, k: k, hidden: hidden) else {
                    return nil
                }
                programs.append(value)
            }
            var slots: [Slot] = []
            for _ in 0 ..< 2 {
                guard let slot = Slot(s: s, k: k, hidden: hidden) else { return nil }
                slots.append(slot)
            }
            self.s = s; self.k = k; self.hidden = hidden
            self.programs = programs
            self.idle = slots
        }

        func take() -> Slot? {
            lock.lock(); let usable = !poisoned; lock.unlock()
            guard usable, available.wait(timeout: .now() + .seconds(10)) == .success else {
                return nil
            }
            lock.lock(); defer { lock.unlock() }
            guard !poisoned, let value = idle.popLast() else {
                available.signal(); return nil
            }
            return value
        }

        func give(_ value: Slot) {
            lock.lock(); idle.append(value); lock.unlock(); available.signal()
        }

        func quarantine(_ value: Slot) {
            lock.lock(); poisoned = true; lock.unlock(); _ = value
        }
    }

    private final class WeightPiece {
        let gate0: [OpaquePointer], gate1: [OpaquePointer]
        let up0: [OpaquePointer], up1: [OpaquePointer]
        let down0: OpaquePointer, down1: OpaquePointer
        init?(k: Int, hidden: Int) {
            var made: [OpaquePointer] = []
            func tensor(_ rows: Int, _ width: Int) -> OpaquePointer? {
                guard let value = h3_ane_tensor_create(Int32(rows), Int32(width)) else { return nil }
                made.append(value); return value
            }
            var gate0: [OpaquePointer] = [], gate1: [OpaquePointer] = []
            var up0: [OpaquePointer] = [], up1: [OpaquePointer] = []
            for _ in 0 ..< contractionSplits {
                guard let g0 = tensor(k / contractionSplits, neuronsPerPiece),
                      let g1 = tensor(k / contractionSplits, neuronsPerPiece),
                      let u0 = tensor(k / contractionSplits, neuronsPerPiece),
                      let u1 = tensor(k / contractionSplits, neuronsPerPiece)
                else {
                    for value in made { h3_ane_tensor_free(value) }
                    return nil
                }
                gate0.append(g0); gate1.append(g1)
                up0.append(u0); up1.append(u1)
            }
            guard let down0 = tensor(neuronsPerPiece, hidden),
                  let down1 = tensor(neuronsPerPiece, hidden)
            else {
                for value in made { h3_ane_tensor_free(value) }
                return nil
            }
            self.gate0 = gate0; self.gate1 = gate1
            self.up0 = up0; self.up1 = up1
            self.down0 = down0; self.down1 = down1
        }
        deinit {
            for value in gate0 + gate1 + up0 + up1 + [down0, down1] {
                h3_ane_tensor_free(value)
            }
        }
    }

    private final class WeightSet {
        weak var fc1: MLXArray?
        weak var fc2: MLXArray?
        let pieces: [WeightPiece]
        init(fc1: MLXArray, fc2: MLXArray, pieces: [WeightPiece]) {
            self.fc1 = fc1; self.fc2 = fc2; self.pieces = pieces
        }
    }

    private struct WeightKey: Hashable {
        let fc1: ObjectIdentifier
        let fc2: ObjectIdentifier
    }

    private static let lock = NSLock()
    nonisolated(unsafe) private static var sessions: [String: Session] = [:]
    nonisolated(unsafe) private static var weightSets: [WeightKey: WeightSet] = [:]
    nonisolated(unsafe) private static var refused: Set<String> = []
    private static let metalDevice = MTLCreateSystemDefaultDevice()

    private static func session(s: Int, k: Int, hidden: Int) -> Session? {
        let key = "\(ANELinearBackend.paddedSequence(s))x\(k)x\(hidden)"
        lock.lock(); defer { lock.unlock() }
        if let cached = sessions[key] { return cached }
        if refused.contains(key) { return nil }
        guard let made = Session(requestedS: s, k: k, hidden: hidden) else {
            refused.insert(key); return nil
        }
        sessions[key] = made
        return made
    }

    private static func weights(fc1: MLXArray, fc2: MLXArray,
                                partition: Partition) -> WeightSet? {
        let key = WeightKey(fc1: ObjectIdentifier(fc1), fc2: ObjectIdentifier(fc2))
        lock.lock()
        weightSets = weightSets.filter { $0.value.fc1 != nil && $0.value.fc2 != nil }
        if let cached = weightSets[key], cached.fc1 === fc1, cached.fc2 === fc2 {
            lock.unlock(); return cached
        }
        lock.unlock()

        let k = fc1.dim(1), hidden = fc2.dim(0), ffn = fc2.dim(1)
        var made: [WeightPiece] = []

        func upload(_ array: MLXArray, to tensor: OpaquePointer,
                    rows: Int, width: Int) -> Bool {
            let packed = MLX.contiguous(array.asType(.float16))
            packed.eval()
            return packed.asData(access: .noCopyIfContiguous).data.withUnsafeBytes { raw in
                guard let base = raw.baseAddress else { return false }
                return h3_ane_tensor_write(tensor, base, Int32(rows), Int32(width))
            }
        }

        func uploadSplit(_ array: MLXArray, to tensors: [OpaquePointer]) -> Bool {
            guard tensors.count == contractionSplits else { return false }
            let packed = MLX.contiguous(array.asType(.float16))
            packed.eval()
            let rows = packed.dim(0), width = packed.dim(1)
            guard rows == k, width == neuronsPerPiece else { return false }
            let rowsPerSplit = rows / contractionSplits
            return packed.asData(access: .noCopyIfContiguous).data.withUnsafeBytes { raw in
                guard let base = raw.baseAddress else { return false }
                for index in 0 ..< contractionSplits {
                    let offset = index * rowsPerSplit * width * MemoryLayout<Float16>.size
                    guard h3_ane_tensor_write(tensors[index], base + offset,
                                              Int32(rowsPerSplit), Int32(width))
                    else { return false }
                }
                return true
            }
        }

        for pieceIndex in 0 ..< activePieces {
            guard let piece = WeightPiece(k: k, hidden: hidden) else { return nil }
            let offset = pieceIndex * neuronsPerPiece
            let r0 = (partition.ane0.lowerBound + offset) ..<
                     (partition.ane0.lowerBound + offset + neuronsPerPiece)
            let r1 = (partition.ane1.lowerBound + offset) ..<
                     (partition.ane1.lowerBound + offset + neuronsPerPiece)
            guard uploadSplit(fc1[r0].transposed(), to: piece.gate0),
                  uploadSplit(fc1[r1].transposed(), to: piece.gate1),
                  uploadSplit(
                    fc1[(ffn + r0.lowerBound) ..< (ffn + r0.upperBound)].transposed(),
                    to: piece.up0),
                  uploadSplit(
                    fc1[(ffn + r1.lowerBound) ..< (ffn + r1.upperBound)].transposed(),
                    to: piece.up1),
                  upload(fc2[0..., r0].transposed(), to: piece.down0,
                         rows: neuronsPerPiece, width: hidden),
                  upload(fc2[0..., r1].transposed(), to: piece.down1,
                         rows: neuronsPerPiece, width: hidden)
            else { return nil }
            made.append(piece)
        }
        let set = WeightSet(fc1: fc1, fc2: fc2, pieces: made)
        lock.lock(); weightSets[key] = set; lock.unlock()
        return set
    }

    private struct Handles: @unchecked Sendable {
        let xs: [OpaquePointer]
        let slotPieces: [Piece]
        let weights: [WeightPiece]
        let programs: [Session.Programs]
        let scale0: Float, scale1: Float
        let s: Int
    }

    private static func fallback(x: MLXArray, fc1: MLXArray, fc2: MLXArray) -> MLXArray {
        let projected = MLX.matmul(x, fc1.transposed())
        let halves = projected.split(parts: 2, axis: -1)
        return MLX.matmul(silu(halves[0]) * halves[1], fc2.transposed())
    }

    /// One complete island whose ANE and GPU partials are in flight. The slot
    /// remains exclusively owned until `value` joins the result; two session
    /// slots let CFG submit the other branch before collecting this one.
    package final class Pending {
        private let gpu: MLXArray
        private let job: Engine.Job
        private let session: Session
        private let slot: Slot
        private let scales: (Float, Float)
        private let rows: Int
        private let hidden: Int
        private let x: MLXArray
        private let fc1: MLXArray
        private let fc2: MLXArray
        private var collected: MLXArray?

        fileprivate init(gpu: MLXArray, job: Engine.Job, session: Session,
                         slot: Slot, scales: (Float, Float), rows: Int, hidden: Int,
                         x: MLXArray, fc1: MLXArray, fc2: MLXArray) {
            self.gpu = gpu; self.job = job; self.session = session; self.slot = slot
            self.scales = scales; self.rows = rows; self.hidden = hidden
            self.x = x; self.fc1 = fc1; self.fc2 = fc2
        }

        package func value() -> MLXArray {
            if let collected { return collected }
            guard job.wait() else {
                session.quarantine(slot)
                ANELinearBackend.recordRoute("mlp island", routed: false)
                let result = ANEMLPIslandBackend.fallback(x: x, fc1: fc1, fc2: fc2)
                collected = result
                return result
            }

            let gpuPartial = MLX.contiguous(gpu)
            gpuPartial.eval()
            let output = MLXArray.zeros([rows, hidden], dtype: .bfloat16)
            let a0 = slot.pieces.map(\.partial0)
            let a1 = slot.pieces.map(\.partial1)
            let merged = ANEMLPIslandBackend.metalDevice.flatMap { device in
                gpuPartial.asMTLBuffer(device: device, noCopy: true).flatMap { gpuBuffer in
                    output.asMTLBuffer(device: device, noCopy: true).map { outputBuffer in
                        a0.withUnsafeBufferPointer { p0 in
                            a1.withUnsafeBufferPointer { p1 in
                                h3_ane_merge_mlp_island_partials(
                                    gpuBuffer.contents(), p0.baseAddress!, 1 / scales.0,
                                    p1.baseAddress!, 1 / scales.1, outputBuffer.contents(),
                                    Int32(rows), Int32(hidden), nil)
                            }
                        }
                    }
                }
            } ?? false
            session.give(slot)
            let result: MLXArray
            if merged {
                ANELinearBackend.recordRoute("mlp island", routed: true)
                result = output
            } else {
                ANELinearBackend.recordRoute("mlp island", routed: false)
                result = ANEMLPIslandBackend.fallback(x: x, fc1: fc1, fc2: fc2)
            }
            collected = result
            return result
        }

        deinit {
            guard collected == nil else { return }
            if job.wait() { session.give(slot) }
            else { session.quarantine(slot) }
        }
    }

    /// Attempts the persistent island. Nil means it declined before any work
    /// was submitted; a returned value is always a complete MLP result.
    package static func project(x: MLXArray, fc1: MLXArray, fc2: MLXArray,
                                blockIndex: Int) -> MLXArray? {
        guard isEnabled else { return nil }
        return beginRoute(x: x, fc1: fc1, fc2: fc2, blockIndex: blockIndex)?.value()
    }

    /// Environment-gated split-phase entry point used by the CFG wavefront.
    package static func begin(x: MLXArray, fc1: MLXArray, fc2: MLXArray,
                              blockIndex: Int) -> Pending? {
        guard isEnabled else { return nil }
        return beginRoute(x: x, fc1: fc1, fc2: fc2, blockIndex: blockIndex)
    }

    /// Testable route without the environment switch. Like
    /// `ANELinearBackend.route`, this still requires validated hardware and
    /// preserves every runtime fallback.
    package static func route(x: MLXArray, fc1: MLXArray, fc2: MLXArray,
                              blockIndex: Int) -> MLXArray? {
        beginRoute(x: x, fc1: fc1, fc2: fc2, blockIndex: blockIndex)?.value()
    }

    /// Why the island declined, printed once, under `H3_ANE_ISLAND_TRACE=1`.
    ///
    /// A decline before submission leaves nothing on the receipt — by design,
    /// since it is not a routing failure — and that silence hid a schedule
    /// measuring itself twice.
    nonisolated(unsafe) private static var tracedDecline = false
    private static let traceEnabled =
        ProcessInfo.processInfo.environment["H3_ANE_ISLAND_TRACE"] == "1"

    private static func decline(_ reason: @autoclosure () -> String) -> Pending? {
        if traceEnabled {
            lock.lock()
            let first = !tracedDecline
            tracedDecline = true
            lock.unlock()
            if first { print("[island] declined: \(reason())") }
        }
        return nil
    }

    package static func beginRoute(x: MLXArray, fc1: MLXArray, fc2: MLXArray,
                                   blockIndex: Int) -> Pending? {
        guard h3_ane_is_available() else { return decline("engine unavailable") }
        guard !QueryTiling.isEnabled else { return decline("query tiling owns the engine") }
        guard x.ndim == 2, x.dtype == .bfloat16 else {
            return decline("x is \(x.ndim)-D \(x.dtype), wanted 2-D bfloat16")
        }
        guard fc1.ndim == 2, fc2.ndim == 2 else { return decline("weights not 2-D") }
        guard blockIndex >= 0, blockIndex < fc2Scales.count else {
            return decline("block \(blockIndex) has no calibrated scale")
        }
        let s = x.dim(0), hidden = x.dim(1), ffn = fc2.dim(1)
        guard hidden == expectedHidden else {
            return decline("hidden \(hidden): x \(x.shape) fc1 \(fc1.shape) fc2 \(fc2.shape)")
        }
        guard fc1.shape == [2 * ffn, hidden], fc2.dim(0) == hidden else {
            return decline("fc1 \(fc1.shape) fc2 \(fc2.shape)")
        }
        guard let partition = partition(ffn: ffn) else { return decline("ffn \(ffn)") }
        guard let session = session(s: s, k: hidden, hidden: hidden) else {
            return decline("no session for s=\(s) k=\(hidden)")
        }
        guard let weights = weights(fc1: fc1, fc2: fc2, partition: partition) else {
            return decline("weight upload failed")
        }
        guard metalDevice != nil else { return decline("no Metal device") }
        guard let slot = session.take() else {
            return decline("no free slot (poisoned or timed out)")
        }

        let source = Stream.withNewDefaultStream(device: .gpu) { () -> MLXArray in
            let value = MLX.contiguous((x * inputScale).transposed().asType(.float16))
            value.eval()
            return value
        }
        let uploaded = source.asData(access: .noCopyIfContiguous).data.withUnsafeBytes { raw in
            guard let base = raw.baseAddress else { return false }
            let kc = hidden / contractionSplits
            for index in 0 ..< contractionSplits {
                let offset = index * kc * s * MemoryLayout<Float16>.size
                guard h3_ane_tensor_write_prefix(slot.xs[index], base + offset,
                                                 Int32(kc), Int32(s))
                else { return false }
            }
            return true
        }
        guard uploaded else { session.give(slot); return nil }

        let scales = fc2Scales[blockIndex]
        let handles = Handles(xs: slot.xs, slotPieces: slot.pieces,
                              weights: weights.pieces,
                              programs: session.programs,
                              scale0: scales.0, scale1: scales.1, s: session.s)
        let job = Engine.shared.submit {
            for index in 0 ..< activePieces {
                let p = handles.slotPieces[index], w = handles.weights[index]
                let programs = handles.programs[index]
                for split in 0 ..< contractionSplits {
                    guard h3_ane_run_pair(
                        programs.gate0[split], handles.xs[split], w.gate0[split], p.gate0[split],
                        programs.gate1[split], handles.xs[split], w.gate1[split], p.gate1[split])
                    else { return false }
                }
                for split in 0 ..< contractionSplits {
                    guard h3_ane_run_pair(
                        programs.up0[split], handles.xs[split], w.up0[split], p.up0[split],
                        programs.up1[split], handles.xs[split], w.up1[split], p.up1[split])
                    else { return false }
                }
                let seam: Bool
                if contractionSplits == 1 {
                    seam = h3_ane_swiglu_transpose_pair_fp16(
                        p.gate0[0], p.up0[0], p.activation0, handles.scale0,
                        p.gate1[0], p.up1[0], p.activation1, handles.scale1,
                        Int32(handles.s), Int32(neuronsPerPiece), 1 / inputScale, nil)
                } else {
                    seam = p.gate0.withUnsafeBufferPointer { gate0 in
                        p.up0.withUnsafeBufferPointer { up0 in
                            p.gate1.withUnsafeBufferPointer { gate1 in
                                p.up1.withUnsafeBufferPointer { up1 in
                                    h3_ane_swiglu_transpose_pair_split4_fp16(
                                        gate0.baseAddress!, up0.baseAddress!,
                                        p.activation0, handles.scale0,
                                        gate1.baseAddress!, up1.baseAddress!,
                                        p.activation1, handles.scale1,
                                        Int32(handles.s), Int32(neuronsPerPiece),
                                        1 / inputScale, nil)
                                }
                            }
                        }
                    }
                }
                guard seam,
                      h3_ane_run_pair(programs.down0, p.activation0, w.down0, p.partial0,
                                      programs.down1, p.activation1, w.down1, p.partial1)
                else { return false }
            }
            return true
        }

        let gpu = Stream.withNewDefaultStream(device: .gpu) { () -> MLXArray in
            func partial(_ range: Range<Int>) -> MLXArray {
                let gate = MLX.matmul(x, fc1[range].transposed())
                let upRange = (ffn + range.lowerBound) ..< (ffn + range.upperBound)
                let up = MLX.matmul(x, fc1[upRange].transposed())
                return MLX.matmul(silu(gate) * up, fc2[0..., range].transposed())
            }
            var output = partial(partition.gpu).asType(.float32)
            let inactiveOffset = activePieces * neuronsPerPiece
            for die in [partition.ane0, partition.ane1] {
                let range = (die.lowerBound + inactiveOffset) ..< die.upperBound
                output = output + partial(range).asType(.float32)
            }
            output = output.asType(.bfloat16)
            MLX.asyncEval(output)
            return output
        }

        return Pending(gpu: gpu, job: job, session: session, slot: slot,
                       scales: scales, rows: s, hidden: hidden,
                       x: x, fc1: fc1, fc2: fc2)
    }
}
